AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation: 
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - n
    - m 
    - x
    - y
    - z
