AllCops:
  NewCops: enable

Metrics/MethodLength:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Style/BlockComments:
  Enabled: false

Style/Documentation: 
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
