AllCops:
  NewCops: enable

Metrics/MethodLength:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - n
    - m 
    - x
    - y
    - z

Style/BlockComments:
  Enabled: false

Style/Documentation: 
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
