"=======================================
" General Settings
"=======================================
filetype plugin indent on
syntax on
set clipboard=unnamedplus     " Share system clipboard
set linebreak                 " Wrap without breaking words
set mouse=a                   " Enable mouse support
set number                    " Show line numbers
set tabstop=2                 " Number of spaces tabs count for
set shiftwidth=2              " Indentation amount
set expandtab                 " Use spaces instead of tabs
set splitbelow                " Horizontal splits below
set guifont=JetBrains\ Mono\ Medium\ 12  " GUI font
set nospell                   " Disable spellcheck

"=======================================
" UI & Editor Behavior
"=======================================
set diffopt+=vertical         " Vertical split for diffs
set signcolumn=yes            " Prevent shifting on diagnostics
set updatetime=300            " Faster CursorHold trigger
set nobackup
set nowritebackup

"=======================================
" Key Mappings
"=======================================

" Move by screen line instead of file line
noremap j gj
noremap k gk

" Go to end of line in insert mode
map <C-a> <ESC>$
imap <C-a> <ESC>A

" Clear search highlights
nnoremap <silent><CR> :noh<CR>

" Toggle NERDTree
nnoremap <C-n> :NERDTreeToggle<CR>

" Paste without overwriting register in visual mode
vnoremap p "0p

" Toggle comments
nnoremap <C-_> :Commentary<CR>
xmap <C-_> :Commentary<CR>

"=======================================
" Filetype Specific Settings
"=======================================

augroup python
  autocmd!
  autocmd FileType python setlocal expandtab shiftwidth=2 softtabstop=2 tabstop=2
augroup END

" Pandoc specific
let g:pandoc#modules#disabled = ["folding", "spell"]

"=======================================
" NERDTree Settings
"=======================================
let g:NERDTreeMinimalMenu=1

"=======================================
" Plugin Management (vim-plug)
"=======================================
call plug#begin('~/.vim/plugged')

" File navigation and git
Plug 'preservim/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'

" Autocompletion and pairs
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'jiangmiao/auto-pairs'

" Syntax and colors
Plug 'tpope/vim-commentary'
Plug 'ap/vim-css-color'
Plug 'vim-pandoc/vim-pandoc'
Plug 'vim-pandoc/vim-pandoc-syntax'
Plug 'patstockwell/vim-monokai-tasty'
Plug 'altercation/vim-colors-solarized'

call plug#end()

colorscheme vim-monokai-tasty

"=======================================
" CoC.nvim Configuration
"=======================================

" Check backspace for autocomplete
function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1] =~# '\s'
endfunction

" Autocomplete triggers
inoremap <silent><expr> <TAB> coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" : coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() :
      \ "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

" Trigger completion
if has('nvim')
  inoremap <silent><expr> <C-Space> coc#refresh()
else
  inoremap <silent><expr> <C-@> coc#refresh()
endif

" Diagnostic navigation
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" Documentation and symbol actions
nnoremap <silent> K :call ShowDocumentation()<CR>
function! ShowDocumentation()
  if CocAction('hasProvider', 'hover')
    call CocActionAsync('doHover')
  else
    call feedkeys('K', 'in')
  endif
endfunction

autocmd CursorHold * silent call CocActionAsync('highlight')

" Symbol renaming
nmap <leader>rn <Plug>(coc-rename)

" Code actions and formatting
xmap <leader>f <Plug>(coc-format-selected)
nmap <leader>f <Plug>(coc-format-selected)
xmap <leader>a <Plug>(coc-codeaction-selected)
nmap <leader>a <Plug>(coc-codeaction-selected)
nmap <leader>ac <Plug>(coc-codeaction)
nmap <leader>qf <Plug>(coc-fix-current)
nmap <leader>cl <Plug>(coc-codelens-action)

" Text objects for function/class
xmap if <Plug>(coc-funcobj-i)
omap if <Plug>(coc-funcobj-i)
xmap af <Plug>(coc-funcobj-a)
omap af <Plug>(coc-funcobj-a)
xmap ic <Plug>(coc-classobj-i)
omap ic <Plug>(coc-classobj-i)
xmap ac <Plug>(coc-classobj-a)
omap ac <Plug>(coc-classobj-a)

" Floating window scrolling
if has('nvim-0.4.0') || has('patch-8.2.0750')
  nnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
  nnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
  inoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" : "\<Right>"
  inoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" : "\<Left>"
  vnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
  vnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
endif

" CoC formatting and signature
augroup mygroup
  autocmd!
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup END

